# Generated by Django 4.0.1 on 2022-01-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_ref', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
    ]
