# Generated by Django 4.0.1 on 2022-01-14 11:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_ref', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('score_ref', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('candidate_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_data.candidate')),
            ],
        ),
    ]
